openapi: 3.0.4
info:
  title: Cofefu
  description: The best (and made up) coffee roaster
  version: 0.0.1

security:
  - bearerAuth: 
    - refresh_token
    - grade
    - give_feedback
    - manage_green_lots
    - manage_lots
    - manage_roasters
    - manage_orders

servers:
  - url: http://localhost:4000/api/
    description: LOCALHOST!!!

paths:
  /auth/login:
    post:
      summary: Login to the system
      description: Login to the system
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: A JSON object containing the user's token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        "401":
          description: Incorrect credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/refresh:
    post:
      summary: Refresh the user's token
      description: Refresh the user's token
      tags:
        - Auth
      security:
        - bearerAuth:
          - refresh_token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        "200":
          description: A JSON object containing the user's token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        "401":
          description: Incorrect refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/register:
    post:
      summary: Register a new user
      description: Register a new user
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        "200":
          description: A JSON object containing the user's token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        "400":
          description: Bad Request
  /green_lots:
    post:
      summary: Creates new green lot.
      tags:
        - Green Lots
        - Inner
      security:
        - bearerAuth:
          - manage_green_lots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GreenLot'
      responses:
        "200":
          description: A JSON array of green coffee lots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GreenLot'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
    RegistrationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    RefreshTokenRequest:
      type: object
      properties:
        refresh_token:
          type: string
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    GreenLot:
      type: object
      properties:
        lot_number:
          type: string
          description: Unique identifier for the green coffee lot
        harvest_date:
          type: string
          format: date
          description: Date when the coffee was harvested
        location:
          $ref: '#/components/schemas/Location'
        processing_method:
          $ref: '#/components/schemas/ProcessingMethod'
        green_lot_stat:
          $ref: '#/components/schemas/GreenLotStat'
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - lot_number
        - harvest_date
        - location
        - processing_method

    Location:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the location
        country_code:
          type: string
          description: ISO country code
        region:
          type: string
          description: Region or state where the coffee was grown
        farm:
          type: string
          description: Name of the farm
        farmer:
          type: string
          description: Name of the farmer
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - country_code
        - region
        - farm
        - farmer

    ProcessingMethod:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the processing method
        name:
          type: string
          description: Name of the processing method
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name

    GreenLotStat:
      type: object
      properties:
        lot_number:
          type: string
          description: Reference to the green lot
        humidity:
          type: number
          format: decimal
          description: Humidity percentage of the green coffee
        aw:
          type: number
          format: decimal
          description: Water activity level
        density:
          type: integer
          description: Density of the green coffee
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - lot_number
        - humidity
        - aw
        - density
